# Generated by Django 6.0.5 on 2026-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('contact_info', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=5)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
